all:
  vars:
    ansible_user: owner # default user for SSH
    ansible_ssh_private_key_file: ~/.ssh/id_rsa

  children:
    workstations: # workstation computers for lab exams
      vars:
        ansible_user: maruthisi # default user for SSH
      hosts:
        ccs-ws006:
          ansible_host: 198.18.1.106
          vms:
            - natrtr
            - vpnrtr
          lxds:
            - corertr
            - dnssrv
            - ldapsrv
            - apisrv
            - lanhost0
            - lanhost1

    vms: # VMs running on either baremetals or in cloud
      hosts:
        natrtr:
          ansible_host: 192.168.255.50
        vpnrtr:
          ansible_host: 192.168.255.49

    lxds: # Containers running on baremetals or VMs
      hosts:
        corertr:
          ansible_host: 192.168.255.1
        ipamsrv:
          ansible_host: 192.168.0.5
        dnssrv:
          ansible_host: 192.168.0.6
        ldapsrv:
          ansible_host: 192.168.0.8
        apisrv:
          ansible_host: 192.168.0.19
        lanhost0:
          ansible_host: 192.168.1.50
        lanhost1:
          ansible_host: 192.168.1.51



